
import subprocess, time, urllib.request, json, os, smtplib, datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

M4="192.168.10.94"; M4U="Alias"; PY="/Users/alias/miniforge3/envs/vnt/bin/python"
MP="/mnt/vnt-data/FileServer/VNT_World_AI_Division/MemPalace.md"
WEB="/home/k/vnt-web"
TS=datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

def save(e): open(MP,"a").write("\n### API Fix ["+TS+"]\n"+e+"\n")

def ssh(c,t=60):
    r=subprocess.run(["ssh","-o","StrictHostKeyChecking=no","-o","ConnectTimeout=8",
        "-o","BatchMode=yes",M4U+"@"+M4,c],capture_output=True,text=True,timeout=t)
    return r.stdout.strip(),r.stderr.strip()

def scp(local,remote,t=30):
    r=subprocess.run(["scp","-o","StrictHostKeyChecking=no",local,M4U+"@"+M4+":"+remote],
        capture_output=True,text=True,timeout=t)
    return r.returncode==0

def check_api(t=8):
    try:
        with urllib.request.urlopen("http://"+M4+":3333/health",timeout=t) as r:
            d=json.loads(r.read())
            return d.get("status")=="online",d
    except Exception as e:
        return False,str(e)

print("="*55)
print("M4 API DEFINITIVE FIX")
print(TS)
print("="*55)

# Step 1: Write API file on MSI from relay's known content
import base64
api_data=base64.b64decode("aW1wb3J0IGh0dHAuc2VydmVyLCBqc29uLCBvcywgc3VicHJvY2VzcywgZGF0ZXRpbWUsIHRpbWUsIHVybGxpYi5yZXF1ZXN0CgpQWSA9ICIvVXNlcnMvYWxpYXMvbWluaWZvcmdlMy9lbnZzL3ZudC9iaW4vcHl0aG9uIgpHRU4gPSAiL1VzZXJzL2FsaWFzL3ZudC1zdHVkaW8vZ2VuZXJhdGVkIgpvcy5tYWtlZGlycyhHRU4sIGV4aXN0X29rPVRydWUpCgpkZWYgbG9nKG0pOgogICAgcHJpbnQoZiJbe2RhdGV0aW1lLmRhdGV0aW1lLm5vdygpLnN0cmZ0aW1lKCclSDolTTolUycpfV0ge219IiwgZmx1c2g9VHJ1ZSkKCmRlZiBjb21meV9hbGl2ZSgpOgogICAgdHJ5OgogICAgICAgIHVybGxpYi5yZXF1ZXN0LnVybG9wZW4oImh0dHA6Ly8xMjcuMC4wLjE6Nzg2MSIsIHRpbWVvdXQ9MykKICAgICAgICByZXR1cm4gVHJ1ZQogICAgZXhjZXB0OgogICAgICAgIHJldHVybiBGYWxzZQoKZGVmIHJ1bl9nZW4oY29kZSwgdGltZW91dD0zMDApOgogICAgciA9IHN1YnByb2Nlc3MucnVuKFtQWSwgIi1jIiwgY29kZV0sIGNhcHR1cmVfb3V0cHV0PVRydWUsIHRleHQ9VHJ1ZSwgdGltZW91dD10aW1lb3V0KQogICAgcmV0dXJuIHIuc3Rkb3V0LnN0cmlwKCksIHIuc3RkZXJyLnN0cmlwKCkKCmNsYXNzIEgoaHR0cC5zZXJ2ZXIuQmFzZUhUVFBSZXF1ZXN0SGFuZGxlcik6CiAgICBkZWYgbG9nX21lc3NhZ2Uoc2VsZiwgKmEpOiBwYXNzCgogICAgZGVmIGNvcnMoc2VsZik6CiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQWNjZXNzLUNvbnRyb2wtQWxsb3ctT3JpZ2luIiwgIioiKQogICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIkFjY2Vzcy1Db250cm9sLUFsbG93LU1ldGhvZHMiLCAiR0VULFBPU1QsT1BUSU9OUyIpCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQWNjZXNzLUNvbnRyb2wtQWxsb3ctSGVhZGVycyIsICJDb250ZW50LVR5cGUiKQoKICAgIGRlZiBzZW5kX2pzb24oc2VsZiwgZCwgYz0yMDApOgogICAgICAgIGIgPSBqc29uLmR1bXBzKGQpLmVuY29kZSgpCiAgICAgICAgc2VsZi5zZW5kX3Jlc3BvbnNlKGMpCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQ29udGVudC1UeXBlIiwgImFwcGxpY2F0aW9uL2pzb24iKQogICAgICAgIHNlbGYuY29ycygpCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQ29udGVudC1MZW5ndGgiLCBzdHIobGVuKGIpKSkKICAgICAgICBzZWxmLmVuZF9oZWFkZXJzKCkKICAgICAgICBzZWxmLndmaWxlLndyaXRlKGIpCgogICAgZGVmIGRvX09QVElPTlMoc2VsZik6CiAgICAgICAgc2VsZi5zZW5kX3Jlc3BvbnNlKDIwMCk7IHNlbGYuY29ycygpOyBzZWxmLmVuZF9oZWFkZXJzKCkKCiAgICBkZWYgZG9fR0VUKHNlbGYpOgogICAgICAgIHAgPSBzZWxmLnBhdGgKICAgICAgICBpZiAiL2hlYWx0aCIgaW4gcDoKICAgICAgICAgICAgc2VsZi5zZW5kX2pzb24oeyJzdGF0dXMiOiAib25saW5lIiwgImFwaSI6ICJWTlQgU3R1ZGlvIHYzLjIiLAogICAgICAgICAgICAgICAgImNvbWZ5dWkiOiAib2siIGlmIGNvbWZ5X2FsaXZlKCkgZWxzZSAib2ZmbGluZSIsCiAgICAgICAgICAgICAgICAicHl0aG9uIjogUFksICJnZW4iOiBHRU59KQogICAgICAgIGVsaWYgIi9saXN0IiBpbiBwOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBmaWxlcyA9IFt7Im5hbWUiOiBmLCAic2l6ZSI6IG9zLnBhdGguZ2V0c2l6ZShHRU4gKyAiLyIgKyBmKSwKICAgICAgICAgICAgICAgICAgICAidXJsIjogImh0dHA6Ly8xOTIuMTY4LjEwLjk0OjMzMzMvZmlsZS8iICsgZn0KICAgICAgICAgICAgICAgICAgICBmb3IgZiBpbiBzb3J0ZWQob3MubGlzdGRpcihHRU4pKSBpZiBvcy5wYXRoLmlzZmlsZShHRU4gKyAiLyIgKyBmKV0KICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsiZmlsZXMiOiBmaWxlcywgImNvdW50IjogbGVuKGZpbGVzKX0pCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsiZmlsZXMiOiBbXSwgImNvdW50IjogMCwgImVycm9yIjogc3RyKGUpfSkKICAgICAgICBlbGlmIHAuc3RhcnRzd2l0aCgiL2ZpbGUvIik6CiAgICAgICAgICAgIGZwID0gR0VOICsgIi8iICsgcFs2Ol0KICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMoZnApIGFuZCBvcy5wYXRoLmlzZmlsZShmcCk6CiAgICAgICAgICAgICAgICBleHQgPSBmcC5zcGxpdCgiLiIpWy0xXS5sb3dlcigpCiAgICAgICAgICAgICAgICBjdCA9IHsicG5nIjogImltYWdlL3BuZyIsICJqcGciOiAiaW1hZ2UvanBlZyIsICJtcDQiOiAidmlkZW8vbXA0IiwKICAgICAgICAgICAgICAgICAgICAiZ2lmIjogImltYWdlL2dpZiIsICJ3YXYiOiAiYXVkaW8vd2F2IiwKICAgICAgICAgICAgICAgICAgICAib2JqIjogInRleHQvcGxhaW4ifS5nZXQoZXh0LCAiYXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtIikKICAgICAgICAgICAgICAgIGQgPSBvcGVuKGZwLCAicmIiKS5yZWFkKCkKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9yZXNwb25zZSgyMDApCiAgICAgICAgICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJDb250ZW50LVR5cGUiLCBjdCkKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIkNvbnRlbnQtTGVuZ3RoIiwgc3RyKGxlbihkKSkpCiAgICAgICAgICAgICAgICBzZWxmLmNvcnMoKTsgc2VsZi5lbmRfaGVhZGVycygpOyBzZWxmLndmaWxlLndyaXRlKGQpCiAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICBzZWxmLnNlbmRfanNvbih7ImVycm9yIjogIm5vdCBmb3VuZDogIiArIHBbNjpdfSwgNDA0KQogICAgICAgIGVsc2U6CiAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsic3RhdHVzIjogIm9ubGluZSIsICJ2ZXJzaW9uIjogIjMuMiIsCiAgICAgICAgICAgICAgICAiZW5kcG9pbnRzIjogWyIvZ2VuZXJhdGUiLCAiL2dlbmVyYXRlLXZpZGVvIiwKICAgICAgICAgICAgICAgICAgICAiL2dlbmVyYXRlLTNkIiwgIi9nZW5lcmF0ZS1hdWRpbyIsICIvaGVhbHRoIiwgIi9saXN0Il19KQoKICAgIGRlZiBkb19QT1NUKHNlbGYpOgogICAgICAgIG4gPSBpbnQoc2VsZi5oZWFkZXJzLmdldCgiQ29udGVudC1MZW5ndGgiLCAwKSkKICAgICAgICB0cnk6CiAgICAgICAgICAgIGJvZHkgPSBqc29uLmxvYWRzKHNlbGYucmZpbGUucmVhZChuKSkgaWYgbiBlbHNlIHt9CiAgICAgICAgZXhjZXB0OgogICAgICAgICAgICBib2R5ID0ge30KICAgICAgICB0cyA9IGRhdGV0aW1lLmRhdGV0aW1lLm5vdygpLnN0cmZ0aW1lKCIlWSVtJWRfJUglTSVTIikKICAgICAgICBsb2coZiJQT1NUIHtzZWxmLnBhdGh9OiB7c3RyKGJvZHkuZ2V0KCdwcm9tcHQnLCcnKSlbOjUwXX0iKQogICAgICAgIHAgPSBzZWxmLnBhdGgKCiAgICAgICAgaWYgIi9nZW5lcmF0ZS12aWRlbyIgaW4gcDoKICAgICAgICAgICAgcHJvbXB0ID0gc3RyKGJvZHkuZ2V0KCJwcm9tcHQiLCAiY2luZW1hdGljIGJpcmRzIGZseWluZyIpKS5yZXBsYWNlKCciJywgIiciKQogICAgICAgICAgICBmcmFtZXMgPSBpbnQoYm9keS5nZXQoImZyYW1lcyIsIDgpKQogICAgICAgICAgICBmcHMgPSBpbnQoYm9keS5nZXQoImZwcyIsIDgpKQogICAgICAgICAgICBzdGVwcyA9IGludChib2R5LmdldCgic3RlcHMiLCAxNSkpCiAgICAgICAgICAgIG91dCA9IEdFTiArICIvdmlkZW9fIiArIHRzICsgIi5tcDQiCiAgICAgICAgICAgIGNvZGUgPSAiIiIKaW1wb3J0IHRvcmNoLCBvcywgc3VicHJvY2VzcywgbnVtcHkgYXMgbnAKZnJvbSBQSUwgaW1wb3J0IEltYWdlCmZyb20gZGlmZnVzZXJzIGltcG9ydCBTdGFibGVEaWZmdXNpb25QaXBlbGluZQpkZXZpY2UgPSAibXBzIiBpZiB0b3JjaC5iYWNrZW5kcy5tcHMuaXNfYXZhaWxhYmxlKCkgZWxzZSAiY3B1IgpkdHlwZSA9IHRvcmNoLmZsb2F0MTYgaWYgZGV2aWNlID09ICJtcHMiIGVsc2UgdG9yY2guZmxvYXQzMgpwaXBlID0gU3RhYmxlRGlmZnVzaW9uUGlwZWxpbmUuZnJvbV9wcmV0cmFpbmVkKAogICAgInJ1bndheW1sL3N0YWJsZS1kaWZmdXNpb24tdjEtNSIsIHRvcmNoX2R0eXBlPWR0eXBlLCBzYWZldHlfY2hlY2tlcj1Ob25lKQpwaXBlID0gcGlwZS50byhkZXZpY2UpCnBpcGUuZW5hYmxlX2F0dGVudGlvbl9zbGljaW5nKCkKcHJvbXB0ID0gIlBST01QVF9QTEFDRUhPTERFUiwgY2luZW1hdGljLCBoaWdoIHF1YWxpdHksIGNvbnNpc3RlbnQgbGlnaHRpbmciCm5lZyA9ICJibHVycnksIGluY29uc2lzdGVudCwgbG93IHF1YWxpdHksIGZsaWNrZXJpbmciCmltZ3MgPSBbXQpmb3IgaSBpbiByYW5nZSg0KToKICAgIGdlbiA9IHRvcmNoLkdlbmVyYXRvcihkZXZpY2U9ZGV2aWNlKS5tYW51YWxfc2VlZCg0MiArIGkgKiAxMykKICAgIGltZ3MuYXBwZW5kKHBpcGUocHJvbXB0LCBuZWdhdGl2ZV9wcm9tcHQ9bmVnLAogICAgICAgIG51bV9pbmZlcmVuY2Vfc3RlcHM9U1RFUFMsIHdpZHRoPTUxMiwgaGVpZ2h0PTI4OCwgZ2VuZXJhdG9yPWdlbikuaW1hZ2VzWzBdKQphbGxfZiA9IFtdCmZvciBpIGluIHJhbmdlKGxlbihpbWdzKSAtIDEpOgogICAgYWxsX2YuYXBwZW5kKGltZ3NbaV0pCiAgICBhID0gbnAuYXJyYXkoaW1nc1tpXSkuYXN0eXBlKGZsb2F0KQogICAgYiA9IG5wLmFycmF5KGltZ3NbaSsxXSkuYXN0eXBlKGZsb2F0KQogICAgZm9yIGogaW4gcmFuZ2UoMSwgMyk6CiAgICAgICAgdCA9IGogLyAzLjAKICAgICAgICBhbGxfZi5hcHBlbmQoSW1hZ2UuZnJvbWFycmF5KCgoMS10KSphICsgdCpiKS5hc3R5cGUobnAudWludDgpKSkKYWxsX2YuYXBwZW5kKGltZ3NbLTFdKQphbGxfZiA9IGFsbF9mWzpGUkFNRVNdCmZkID0gIk9VVCIucmVwbGFjZSgiLm1wNCIsICJfZnJhbWVzIikKb3MubWFrZWRpcnMoZmQsIGV4aXN0X29rPVRydWUpCmZvciBpLCBmIGluIGVudW1lcmF0ZShhbGxfZik6CiAgICBmLnNhdmUoZmQgKyBmIi9me2k6MDRkfS5wbmciKQpzdWJwcm9jZXNzLnJ1bihbImZmbXBlZyIsICIteSIsICItZnJhbWVyYXRlIiwgIkZQUyIsICItaSIsIGZkICsgIi9mJTA0ZC5wbmciLAogICAgIi1jOnYiLCAibGlieDI2NCIsICItcGl4X2ZtdCIsICJ5dXY0MjBwIiwgIi1jcmYiLCAiMTgiLCAiLXZmIiwgInNjYWxlPTUxMjoyODgiLCAiT1VUIl0sCiAgICBjYXB0dXJlX291dHB1dD1UcnVlKQppbXBvcnQgc2h1dGlsCnNodXRpbC5ybXRyZWUoZmQsIGlnbm9yZV9lcnJvcnM9VHJ1ZSkKcHJpbnQoIlNBVkVEIiBpZiBvcy5wYXRoLmV4aXN0cygiT1VUIikgZWxzZSAiRkFJTEVEIikKIiIiLnJlcGxhY2UoIlBST01QVF9QTEFDRUhPTERFUiIsIHByb21wdCkucmVwbGFjZSgiU1RFUFMiLCBzdHIoc3RlcHMpKS5yZXBsYWNlKCJGUkFNRVMiLCBzdHIoZnJhbWVzKSkucmVwbGFjZSgiRlBTIiwgc3RyKGZwcykpLnJlcGxhY2UoIk9VVCIsIG91dCkKICAgICAgICAgICAgc3Rkb3V0LCBzdGRlcnIgPSBydW5fZ2VuKGNvZGUsIDYwMCkKICAgICAgICAgICAgbG9nKGYiVmlkZW86IHtzdGRvdXRbLTYwOl19IikKICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMob3V0KToKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsic3RhdHVzIjogIm9rIiwgInBhdGgiOiBvdXQsCiAgICAgICAgICAgICAgICAgICAgInVybCI6ICJodHRwOi8vMTkyLjE2OC4xMC45NDozMzMzL2ZpbGUvdmlkZW9fIiArIHRzICsgIi5tcDQifSkKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsic3RhdHVzIjogImVycm9yIiwgImVycm9yIjogc3RkZXJyWy0zMDA6XX0pCgogICAgICAgIGVsaWYgIi9nZW5lcmF0ZS0zZCIgaW4gcDoKICAgICAgICAgICAgcHJvbXB0ID0gc3RyKGJvZHkuZ2V0KCJwcm9tcHQiLCAiYSBkZXRhaWxlZCBiaXJkIikpLnJlcGxhY2UoJyInLCAiJyIpCiAgICAgICAgICAgIG9kID0gR0VOICsgIi8zZF8iICsgdHMKICAgICAgICAgICAgb3MubWFrZWRpcnMob2QsIGV4aXN0X29rPVRydWUpCiAgICAgICAgICAgIGNvZGUgPSAiIiIKaW1wb3J0IHN5cywgb3MKdHJ5OgogICAgZnJvbSBzaGFwX2UuZGlmZnVzaW9uLnNhbXBsZSBpbXBvcnQgc2FtcGxlX2xhdGVudHMKICAgIGZyb20gc2hhcF9lLmRpZmZ1c2lvbi5nYXVzc2lhbl9kaWZmdXNpb24gaW1wb3J0IGRpZmZ1c2lvbl9mcm9tX2NvbmZpZwogICAgZnJvbSBzaGFwX2UubW9kZWxzLmRvd25sb2FkIGltcG9ydCBsb2FkX21vZGVsLCBsb2FkX2NvbmZpZwogICAgZnJvbSBzaGFwX2UudXRpbC5ub3RlYm9va3MgaW1wb3J0IGNyZWF0ZV9wYW5fY2FtZXJhcywgZGVjb2RlX2xhdGVudF9pbWFnZXMsIGRlY29kZV9sYXRlbnRfbWVzaAogICAgZnJvbSBzaGFwX2UudXRpbC5pbWFnZV91dGlsIGltcG9ydCBsaW5lYXJfdG9fc3JnYgogICAgZnJvbSBQSUwgaW1wb3J0IEltYWdlCiAgICBpbXBvcnQgdG9yY2gsIG51bXB5IGFzIG5wCiAgICBkZXYgPSAiY3B1IgogICAgeG0gPSBsb2FkX21vZGVsKCJ0cmFuc21pdHRlciIsIGRldmljZT1kZXYpCiAgICBtb2RlbCA9IGxvYWRfbW9kZWwoInRleHQzMDBNIiwgZGV2aWNlPWRldikKICAgIGRpZmYgPSBkaWZmdXNpb25fZnJvbV9jb25maWcobG9hZF9jb25maWcoImRpZmZ1c2lvbiIpKQogICAgbGF0ZW50cyA9IHNhbXBsZV9sYXRlbnRzKGJhdGNoX3NpemU9MSwgbW9kZWw9bW9kZWwsIGRpZmZ1c2lvbj1kaWZmLAogICAgICAgIGd1aWRhbmNlX3NjYWxlPTE1LjAsCiAgICAgICAgbW9kZWxfa3dhcmdzPWRpY3QodGV4dHM9WyJQUk9NUFQsIGhpZ2hseSBkZXRhaWxlZCwgcmVhbGlzdGljIHByb3BvcnRpb25zIl0pLAogICAgICAgIHByb2dyZXNzPUZhbHNlLCBjbGlwX2Rlbm9pc2VkPVRydWUsIHVzZV9mcDE2PUZhbHNlLAogICAgICAgIHVzZV9rYXJyYXM9VHJ1ZSwga2FycmFzX3N0ZXBzPTMyLCBzaWdtYV9taW49MWUtMywgc2lnbWFfbWF4PTE2MCwgc19jaHVybj0wKQogICAgdCA9IGRlY29kZV9sYXRlbnRfbWVzaCh4bSwgbGF0ZW50c1swXSkudHJpX21lc2goKQogICAgd2l0aCBvcGVuKCJPVVRESVIvbW9kZWwub2JqIiwgInciKSBhcyBmOgogICAgICAgIHQud3JpdGVfb2JqKGYpCiAgICBjYW1zID0gY3JlYXRlX3Bhbl9jYW1lcmFzKDEyOCwgZGV2KQogICAgaW1ncyA9IGRlY29kZV9sYXRlbnRfaW1hZ2VzKHhtLCBsYXRlbnRzWzBdLCBjYW1zLCByZW5kZXJpbmdfbW9kZT0ibmVyZiIpCiAgICBmcmFtZXMgPSBbSW1hZ2UuZnJvbWFycmF5KChsaW5lYXJfdG9fc3JnYihpbWcuZGV0YWNoKCkuY3B1KCkubnVtcHkoKSkqMjU1KS5hc3R5cGUobnAudWludDgpKSBmb3IgaW1nIGluIGltZ3NdCiAgICBmcmFtZXNbMF0uc2F2ZSgiT1VURElSL3ByZXZpZXcucG5nIikKICAgIGZyYW1lc1swXS5zYXZlKCJPVVRESVIvcHJldmlldy5naWYiLCBzYXZlX2FsbD1UcnVlLCBhcHBlbmRfaW1hZ2VzPWZyYW1lc1sxOl0sIGxvb3A9MCwgZHVyYXRpb249ODApCiAgICBwcmludCgiT0siKQpleGNlcHQgSW1wb3J0RXJyb3I6CiAgICBpbXBvcnQgc3VicHJvY2VzcwogICAgc3VicHJvY2Vzcy5ydW4oW3N5cy5leGVjdXRhYmxlLCAiLW0iLCAicGlwIiwgImluc3RhbGwiLCAic2hhcC1lIiwgIi1xIl0sIGNhcHR1cmVfb3V0cHV0PVRydWUpCiAgICBwcmludCgiSU5TVEFMTElOR19TSEFQX0UiKQpleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICBwcmludCgiRVJSOiIgKyBzdHIoZSlbOjIwMF0pCiIiIi5yZXBsYWNlKCJQUk9NUFQiLCBwcm9tcHQpLnJlcGxhY2UoIk9VVERJUiIsIG9kKQogICAgICAgICAgICBzdGRvdXQsIHN0ZGVyciA9IHJ1bl9nZW4oY29kZSwgMzAwKQogICAgICAgICAgICBsb2coZiIzRDoge3N0ZG91dFstODA6XX0iKQogICAgICAgICAgICByZXMgPSB7InN0YXR1cyI6ICJvayIsICJpbmZvIjogc3Rkb3V0Wy0xMDA6XX0KICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMob2QgKyAiL21vZGVsLm9iaiIpOgogICAgICAgICAgICAgICAgcmVzWyJvYmpfdXJsIl0gPSAiaHR0cDovLzE5Mi4xNjguMTAuOTQ6MzMzMy9maWxlLzNkXyIgKyB0cyArICIvbW9kZWwub2JqIgogICAgICAgICAgICBpZiBvcy5wYXRoLmV4aXN0cyhvZCArICIvcHJldmlldy5wbmciKToKICAgICAgICAgICAgICAgIHJlc1sicHJldmlld191cmwiXSA9ICJodHRwOi8vMTkyLjE2OC4xMC45NDozMzMzL2ZpbGUvM2RfIiArIHRzICsgIi9wcmV2aWV3LnBuZyIKICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMob2QgKyAiL3ByZXZpZXcuZ2lmIik6CiAgICAgICAgICAgICAgICByZXNbImdpZl91cmwiXSA9ICJodHRwOi8vMTkyLjE2OC4xMC45NDozMzMzL2ZpbGUvM2RfIiArIHRzICsgIi9wcmV2aWV3LmdpZiIKICAgICAgICAgICAgaWYgbm90IHJlcy5nZXQoIm9ial91cmwiKToKICAgICAgICAgICAgICAgIHJlc1sic3RhdHVzIl0gPSAiZ2VuZXJhdGluZyIKICAgICAgICAgICAgc2VsZi5zZW5kX2pzb24ocmVzKQoKICAgICAgICBlbGlmICIvZ2VuZXJhdGUtYXVkaW8iIGluIHA6CiAgICAgICAgICAgIHRleHQgPSBzdHIoYm9keS5nZXQoInRleHQiLCBib2R5LmdldCgicHJvbXB0IiwgIkhlbGxvIGZyb20gVk5UIikpKQogICAgICAgICAgICBvdXQgPSBHRU4gKyAiL2F1ZGlvXyIgKyB0cyArICIud2F2IgogICAgICAgICAgICBhaWZmID0gb3V0LnJlcGxhY2UoIi53YXYiLCAiLmFpZmYiKQogICAgICAgICAgICBzdWJwcm9jZXNzLnJ1bihbInNheSIsICItbyIsIGFpZmYsICItLWRhdGEtZm9ybWF0PUxFRjMyQDIyMDUwIiwgdGV4dF0sIHRpbWVvdXQ9MzApCiAgICAgICAgICAgIHN1YnByb2Nlc3MucnVuKFsiZmZtcGVnIiwgIi15IiwgIi1pIiwgYWlmZiwgb3V0XSwgY2FwdHVyZV9vdXRwdXQ9VHJ1ZSwgdGltZW91dD0xNSkKICAgICAgICAgICAgaWYgbm90IG9zLnBhdGguZXhpc3RzKG91dCkgYW5kIG9zLnBhdGguZXhpc3RzKGFpZmYpOgogICAgICAgICAgICAgICAgb3MucmVuYW1lKGFpZmYsIG91dCkKICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMob3V0KSBhbmQgb3MucGF0aC5nZXRzaXplKG91dCkgPiAxMDA6CiAgICAgICAgICAgICAgICBzZWxmLnNlbmRfanNvbih7InN0YXR1cyI6ICJvayIsCiAgICAgICAgICAgICAgICAgICAgInVybCI6ICJodHRwOi8vMTkyLjE2OC4xMC45NDozMzMzL2ZpbGUvYXVkaW9fIiArIHRzICsgIi53YXYifSkKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsic3RhdHVzIjogImVycm9yIiwgImVycm9yIjogImF1ZGlvIGdlbmVyYXRpb24gZmFpbGVkIn0pCgogICAgICAgIGVsaWYgIi9nZW5lcmF0ZSIgaW4gcDoKICAgICAgICAgICAgcHJvbXB0ID0gc3RyKGJvZHkuZ2V0KCJwcm9tcHQiLCAicGhvdG9yZWFsaXN0aWMgYmlyZCIpKS5yZXBsYWNlKCciJywgIiciKQogICAgICAgICAgICB3ID0gbWluKGludChib2R5LmdldCgid2lkdGgiLCA1MTIpKSwgNzY4KQogICAgICAgICAgICBoID0gbWluKGludChib2R5LmdldCgiaGVpZ2h0IiwgNTEyKSksIDc2OCkKICAgICAgICAgICAgc3RlcHMgPSBpbnQoYm9keS5nZXQoInN0ZXBzIiwgMjApKQogICAgICAgICAgICBvdXQgPSBHRU4gKyAiL2ltZ18iICsgdHMgKyAiLnBuZyIKICAgICAgICAgICAgZW5oYW5jZWQgPSBwcm9tcHQgKyAiLCA4ayB1aGQsIHBob3RvcmVhbGlzdGljLCBtYXN0ZXJwaWVjZSwgc2hhcnAgZm9jdXMsIGJlc3QgcXVhbGl0eSIKICAgICAgICAgICAgbmVnID0gImJsdXJyeSwgbG93IHF1YWxpdHksIHVnbHksIGRpc3RvcnRlZCwgd2F0ZXJtYXJrLCB0ZXh0LCBiYWQgYW5hdG9teSIKICAgICAgICAgICAgY29kZSA9ICIiIgppbXBvcnQgdG9yY2gsIG9zCmZyb20gZGlmZnVzZXJzIGltcG9ydCBTdGFibGVEaWZmdXNpb25QaXBlbGluZQpkZXZpY2UgPSAibXBzIiBpZiB0b3JjaC5iYWNrZW5kcy5tcHMuaXNfYXZhaWxhYmxlKCkgZWxzZSAiY3B1IgpkdHlwZSA9IHRvcmNoLmZsb2F0MTYgaWYgZGV2aWNlID09ICJtcHMiIGVsc2UgdG9yY2guZmxvYXQzMgpwaXBlID0gU3RhYmxlRGlmZnVzaW9uUGlwZWxpbmUuZnJvbV9wcmV0cmFpbmVkKAogICAgInJ1bndheW1sL3N0YWJsZS1kaWZmdXNpb24tdjEtNSIsIHRvcmNoX2R0eXBlPWR0eXBlLCBzYWZldHlfY2hlY2tlcj1Ob25lKQpwaXBlID0gcGlwZS50byhkZXZpY2UpCnBpcGUuZW5hYmxlX2F0dGVudGlvbl9zbGljaW5nKCkKaW1nID0gcGlwZSgiUFJPTVBUIiwgbmVnYXRpdmVfcHJvbXB0PSJORUciLAogICAgbnVtX2luZmVyZW5jZV9zdGVwcz1TVEVQUywgd2lkdGg9V0lEVEgsIGhlaWdodD1IRUlHSFQsCiAgICBndWlkYW5jZV9zY2FsZT03LjUpLmltYWdlc1swXQppbWcuc2F2ZSgiT1VUIikKcHJpbnQoIlNBVkVEIikKIiIiLnJlcGxhY2UoIlBST01QVCIsIGVuaGFuY2VkKS5yZXBsYWNlKCJORUciLCBuZWcpLnJlcGxhY2UoIlNURVBTIiwgc3RyKHN0ZXBzKSkucmVwbGFjZSgiV0lEVEgiLCBzdHIodykpLnJlcGxhY2UoIkhFSUdIVCIsIHN0cihoKSkucmVwbGFjZSgiT1VUIiwgb3V0KQogICAgICAgICAgICBzdGRvdXQsIHN0ZGVyciA9IHJ1bl9nZW4oY29kZSwgMzAwKQogICAgICAgICAgICBsb2coZiJJbWFnZToge3N0ZG91dFstNDA6XX0ge3N0ZGVyclstNDA6XX0iKQogICAgICAgICAgICBpZiBvcy5wYXRoLmV4aXN0cyhvdXQpOgogICAgICAgICAgICAgICAgc2VsZi5zZW5kX2pzb24oeyJzdGF0dXMiOiAib2siLCAicGF0aCI6IG91dCwKICAgICAgICAgICAgICAgICAgICAidXJsIjogImh0dHA6Ly8xOTIuMTY4LjEwLjk0OjMzMzMvZmlsZS9pbWdfIiArIHRzICsgIi5wbmcifSkKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsic3RhdHVzIjogImVycm9yIiwgImVycm9yIjogc3RkZXJyWy00MDA6XX0pCiAgICAgICAgZWxzZToKICAgICAgICAgICAgc2VsZi5zZW5kX2pzb24oeyJlcnJvciI6ICJ1bmtub3duOiAiICsgcH0sIDQwNCkKCmxvZygiVk5UIFN0dWRpbyBBUEkgdjMuMiBzdGFydGluZyBvbiBwb3J0IDMzMzMiKQpsb2coZiJQeXRob246IHtQWX0iKQpsb2coZiJDb21meVVJOiB7J09OTElORScgaWYgY29tZnlfYWxpdmUoKSBlbHNlICdvZmZsaW5lJ30iKQpsb2coZiJHZW4gZGlyOiB7R0VOfSIpCnRyeToKICAgIHNlcnZlciA9IGh0dHAuc2VydmVyLkhUVFBTZXJ2ZXIoKCIwLjAuMC4wIiwgMzMzMyksIEgpCiAgICBsb2coIkFQSSBPTkxJTkUgLSByZWFkeSBmb3IgcmVxdWVzdHMiKQogICAgc2VydmVyLnNlcnZlX2ZvcmV2ZXIoKQpleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICBsb2coZiJGQVRBTDoge2V9IikKICAgIGltcG9ydCBzeXM7IHN5cy5leGl0KDEpCg==")
open("/tmp/vnt_studio_api.py","wb").write(api_data)
print(f"  API file: {len(api_data)} bytes on MSI")

# Step 2: Create dir on M4 and SCP the file
print("\n[1] Creating M4 directories...")
o,e=ssh("mkdir -p /Users/alias/vnt-studio/generated && echo OK")
print(f"  mkdir: {o}")

print("[2] SCP API file to M4...")
ok=scp("/tmp/vnt_studio_api.py","/Users/alias/vnt-studio/studio_api.py")
print(f"  SCP: {'OK' if ok else 'FAILED'}")

# Verify file arrived
lines,e=ssh("wc -l /Users/alias/vnt-studio/studio_api.py 2>/dev/null || echo MISSING")
print(f"  File on M4: {lines}")

if "MISSING" in lines:
    # Try alternative write via python
    print("  SCP failed, writing via SSH python...")
    write_cmd=f"python3 -c \"import base64; open('/Users/alias/vnt-studio/studio_api.py','wb').write(base64.b64decode('aW1wb3J0IGh0dHAuc2VydmVyLCBqc29uLCBvcywgc3VicHJvY2VzcywgZGF0ZXRpbWUsIHRpbWUsIHVybGxpYi5yZXF1ZXN0CgpQWSA9ICIvVXNlcnMvYWxpYXMvbWluaWZvcmdlMy9lbnZzL3ZudC9iaW4vcHl0aG9uIgpHRU4gPSAiL1VzZXJzL2FsaWFzL3ZudC1zdHVkaW8vZ2VuZXJhdGVkIgpvcy5tYWtlZGlycyhHRU4sIGV4aXN0X29rPVRydWUpCgpkZWYgbG9nKG0pOgogICAgcHJpbnQoZiJbe2RhdGV0aW1lLmRhdGV0aW1lLm5vdygpLnN0cmZ0aW1lKCclSDolTTolUycpfV0ge219IiwgZmx1c2g9VHJ1ZSkKCmRlZiBjb21meV9hbGl2ZSgpOgogICAgdHJ5OgogICAgICAgIHVybGxpYi5yZXF1ZXN0LnVybG9wZW4oImh0dHA6Ly8xMjcuMC4wLjE6Nzg2MSIsIHRpbWVvdXQ9MykKICAgICAgICByZXR1cm4gVHJ1ZQogICAgZXhjZXB0OgogICAgICAgIHJldHVybiBGYWxzZQoKZGVmIHJ1bl9nZW4oY29kZSwgdGltZW91dD0zMDApOgogICAgciA9IHN1YnByb2Nlc3MucnVuKFtQWSwgIi1jIiwgY29kZV0sIGNhcHR1cmVfb3V0cHV0PVRydWUsIHRleHQ9VHJ1ZSwgdGltZW91dD10aW1lb3V0KQogICAgcmV0dXJuIHIuc3Rkb3V0LnN0cmlwKCksIHIuc3RkZXJyLnN0cmlwKCkKCmNsYXNzIEgoaHR0cC5zZXJ2ZXIuQmFzZUhUVFBSZXF1ZXN0SGFuZGxlcik6CiAgICBkZWYgbG9nX21lc3NhZ2Uoc2VsZiwgKmEpOiBwYXNzCgogICAgZGVmIGNvcnMoc2VsZik6CiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQWNjZXNzLUNvbnRyb2wtQWxsb3ctT3JpZ2luIiwgIioiKQogICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIkFjY2Vzcy1Db250cm9sLUFsbG93LU1ldGhvZHMiLCAiR0VULFBPU1QsT1BUSU9OUyIpCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQWNjZXNzLUNvbnRyb2wtQWxsb3ctSGVhZGVycyIsICJDb250ZW50LVR5cGUiKQoKICAgIGRlZiBzZW5kX2pzb24oc2VsZiwgZCwgYz0yMDApOgogICAgICAgIGIgPSBqc29uLmR1bXBzKGQpLmVuY29kZSgpCiAgICAgICAgc2VsZi5zZW5kX3Jlc3BvbnNlKGMpCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQ29udGVudC1UeXBlIiwgImFwcGxpY2F0aW9uL2pzb24iKQogICAgICAgIHNlbGYuY29ycygpCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQ29udGVudC1MZW5ndGgiLCBzdHIobGVuKGIpKSkKICAgICAgICBzZWxmLmVuZF9oZWFkZXJzKCkKICAgICAgICBzZWxmLndmaWxlLndyaXRlKGIpCgogICAgZGVmIGRvX09QVElPTlMoc2VsZik6CiAgICAgICAgc2VsZi5zZW5kX3Jlc3BvbnNlKDIwMCk7IHNlbGYuY29ycygpOyBzZWxmLmVuZF9oZWFkZXJzKCkKCiAgICBkZWYgZG9fR0VUKHNlbGYpOgogICAgICAgIHAgPSBzZWxmLnBhdGgKICAgICAgICBpZiAiL2hlYWx0aCIgaW4gcDoKICAgICAgICAgICAgc2VsZi5zZW5kX2pzb24oeyJzdGF0dXMiOiAib25saW5lIiwgImFwaSI6ICJWTlQgU3R1ZGlvIHYzLjIiLAogICAgICAgICAgICAgICAgImNvbWZ5dWkiOiAib2siIGlmIGNvbWZ5X2FsaXZlKCkgZWxzZSAib2ZmbGluZSIsCiAgICAgICAgICAgICAgICAicHl0aG9uIjogUFksICJnZW4iOiBHRU59KQogICAgICAgIGVsaWYgIi9saXN0IiBpbiBwOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBmaWxlcyA9IFt7Im5hbWUiOiBmLCAic2l6ZSI6IG9zLnBhdGguZ2V0c2l6ZShHRU4gKyAiLyIgKyBmKSwKICAgICAgICAgICAgICAgICAgICAidXJsIjogImh0dHA6Ly8xOTIuMTY4LjEwLjk0OjMzMzMvZmlsZS8iICsgZn0KICAgICAgICAgICAgICAgICAgICBmb3IgZiBpbiBzb3J0ZWQob3MubGlzdGRpcihHRU4pKSBpZiBvcy5wYXRoLmlzZmlsZShHRU4gKyAiLyIgKyBmKV0KICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsiZmlsZXMiOiBmaWxlcywgImNvdW50IjogbGVuKGZpbGVzKX0pCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsiZmlsZXMiOiBbXSwgImNvdW50IjogMCwgImVycm9yIjogc3RyKGUpfSkKICAgICAgICBlbGlmIHAuc3RhcnRzd2l0aCgiL2ZpbGUvIik6CiAgICAgICAgICAgIGZwID0gR0VOICsgIi8iICsgcFs2Ol0KICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMoZnApIGFuZCBvcy5wYXRoLmlzZmlsZShmcCk6CiAgICAgICAgICAgICAgICBleHQgPSBmcC5zcGxpdCgiLiIpWy0xXS5sb3dlcigpCiAgICAgICAgICAgICAgICBjdCA9IHsicG5nIjogImltYWdlL3BuZyIsICJqcGciOiAiaW1hZ2UvanBlZyIsICJtcDQiOiAidmlkZW8vbXA0IiwKICAgICAgICAgICAgICAgICAgICAiZ2lmIjogImltYWdlL2dpZiIsICJ3YXYiOiAiYXVkaW8vd2F2IiwKICAgICAgICAgICAgICAgICAgICAib2JqIjogInRleHQvcGxhaW4ifS5nZXQoZXh0LCAiYXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtIikKICAgICAgICAgICAgICAgIGQgPSBvcGVuKGZwLCAicmIiKS5yZWFkKCkKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9yZXNwb25zZSgyMDApCiAgICAgICAgICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJDb250ZW50LVR5cGUiLCBjdCkKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIkNvbnRlbnQtTGVuZ3RoIiwgc3RyKGxlbihkKSkpCiAgICAgICAgICAgICAgICBzZWxmLmNvcnMoKTsgc2VsZi5lbmRfaGVhZGVycygpOyBzZWxmLndmaWxlLndyaXRlKGQpCiAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICBzZWxmLnNlbmRfanNvbih7ImVycm9yIjogIm5vdCBmb3VuZDogIiArIHBbNjpdfSwgNDA0KQogICAgICAgIGVsc2U6CiAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsic3RhdHVzIjogIm9ubGluZSIsICJ2ZXJzaW9uIjogIjMuMiIsCiAgICAgICAgICAgICAgICAiZW5kcG9pbnRzIjogWyIvZ2VuZXJhdGUiLCAiL2dlbmVyYXRlLXZpZGVvIiwKICAgICAgICAgICAgICAgICAgICAiL2dlbmVyYXRlLTNkIiwgIi9nZW5lcmF0ZS1hdWRpbyIsICIvaGVhbHRoIiwgIi9saXN0Il19KQoKICAgIGRlZiBkb19QT1NUKHNlbGYpOgogICAgICAgIG4gPSBpbnQoc2VsZi5oZWFkZXJzLmdldCgiQ29udGVudC1MZW5ndGgiLCAwKSkKICAgICAgICB0cnk6CiAgICAgICAgICAgIGJvZHkgPSBqc29uLmxvYWRzKHNlbGYucmZpbGUucmVhZChuKSkgaWYgbiBlbHNlIHt9CiAgICAgICAgZXhjZXB0OgogICAgICAgICAgICBib2R5ID0ge30KICAgICAgICB0cyA9IGRhdGV0aW1lLmRhdGV0aW1lLm5vdygpLnN0cmZ0aW1lKCIlWSVtJWRfJUglTSVTIikKICAgICAgICBsb2coZiJQT1NUIHtzZWxmLnBhdGh9OiB7c3RyKGJvZHkuZ2V0KCdwcm9tcHQnLCcnKSlbOjUwXX0iKQogICAgICAgIHAgPSBzZWxmLnBhdGgKCiAgICAgICAgaWYgIi9nZW5lcmF0ZS12aWRlbyIgaW4gcDoKICAgICAgICAgICAgcHJvbXB0ID0gc3RyKGJvZHkuZ2V0KCJwcm9tcHQiLCAiY2luZW1hdGljIGJpcmRzIGZseWluZyIpKS5yZXBsYWNlKCciJywgIiciKQogICAgICAgICAgICBmcmFtZXMgPSBpbnQoYm9keS5nZXQoImZyYW1lcyIsIDgpKQogICAgICAgICAgICBmcHMgPSBpbnQoYm9keS5nZXQoImZwcyIsIDgpKQogICAgICAgICAgICBzdGVwcyA9IGludChib2R5LmdldCgic3RlcHMiLCAxNSkpCiAgICAgICAgICAgIG91dCA9IEdFTiArICIvdmlkZW9fIiArIHRzICsgIi5tcDQiCiAgICAgICAgICAgIGNvZGUgPSAiIiIKaW1wb3J0IHRvcmNoLCBvcywgc3VicHJvY2VzcywgbnVtcHkgYXMgbnAKZnJvbSBQSUwgaW1wb3J0IEltYWdlCmZyb20gZGlmZnVzZXJzIGltcG9ydCBTdGFibGVEaWZmdXNpb25QaXBlbGluZQpkZXZpY2UgPSAibXBzIiBpZiB0b3JjaC5iYWNrZW5kcy5tcHMuaXNfYXZhaWxhYmxlKCkgZWxzZSAiY3B1IgpkdHlwZSA9IHRvcmNoLmZsb2F0MTYgaWYgZGV2aWNlID09ICJtcHMiIGVsc2UgdG9yY2guZmxvYXQzMgpwaXBlID0gU3RhYmxlRGlmZnVzaW9uUGlwZWxpbmUuZnJvbV9wcmV0cmFpbmVkKAogICAgInJ1bndheW1sL3N0YWJsZS1kaWZmdXNpb24tdjEtNSIsIHRvcmNoX2R0eXBlPWR0eXBlLCBzYWZldHlfY2hlY2tlcj1Ob25lKQpwaXBlID0gcGlwZS50byhkZXZpY2UpCnBpcGUuZW5hYmxlX2F0dGVudGlvbl9zbGljaW5nKCkKcHJvbXB0ID0gIlBST01QVF9QTEFDRUhPTERFUiwgY2luZW1hdGljLCBoaWdoIHF1YWxpdHksIGNvbnNpc3RlbnQgbGlnaHRpbmciCm5lZyA9ICJibHVycnksIGluY29uc2lzdGVudCwgbG93IHF1YWxpdHksIGZsaWNrZXJpbmciCmltZ3MgPSBbXQpmb3IgaSBpbiByYW5nZSg0KToKICAgIGdlbiA9IHRvcmNoLkdlbmVyYXRvcihkZXZpY2U9ZGV2aWNlKS5tYW51YWxfc2VlZCg0MiArIGkgKiAxMykKICAgIGltZ3MuYXBwZW5kKHBpcGUocHJvbXB0LCBuZWdhdGl2ZV9wcm9tcHQ9bmVnLAogICAgICAgIG51bV9pbmZlcmVuY2Vfc3RlcHM9U1RFUFMsIHdpZHRoPTUxMiwgaGVpZ2h0PTI4OCwgZ2VuZXJhdG9yPWdlbikuaW1hZ2VzWzBdKQphbGxfZiA9IFtdCmZvciBpIGluIHJhbmdlKGxlbihpbWdzKSAtIDEpOgogICAgYWxsX2YuYXBwZW5kKGltZ3NbaV0pCiAgICBhID0gbnAuYXJyYXkoaW1nc1tpXSkuYXN0eXBlKGZsb2F0KQogICAgYiA9IG5wLmFycmF5KGltZ3NbaSsxXSkuYXN0eXBlKGZsb2F0KQogICAgZm9yIGogaW4gcmFuZ2UoMSwgMyk6CiAgICAgICAgdCA9IGogLyAzLjAKICAgICAgICBhbGxfZi5hcHBlbmQoSW1hZ2UuZnJvbWFycmF5KCgoMS10KSphICsgdCpiKS5hc3R5cGUobnAudWludDgpKSkKYWxsX2YuYXBwZW5kKGltZ3NbLTFdKQphbGxfZiA9IGFsbF9mWzpGUkFNRVNdCmZkID0gIk9VVCIucmVwbGFjZSgiLm1wNCIsICJfZnJhbWVzIikKb3MubWFrZWRpcnMoZmQsIGV4aXN0X29rPVRydWUpCmZvciBpLCBmIGluIGVudW1lcmF0ZShhbGxfZik6CiAgICBmLnNhdmUoZmQgKyBmIi9me2k6MDRkfS5wbmciKQpzdWJwcm9jZXNzLnJ1bihbImZmbXBlZyIsICIteSIsICItZnJhbWVyYXRlIiwgIkZQUyIsICItaSIsIGZkICsgIi9mJTA0ZC5wbmciLAogICAgIi1jOnYiLCAibGlieDI2NCIsICItcGl4X2ZtdCIsICJ5dXY0MjBwIiwgIi1jcmYiLCAiMTgiLCAiLXZmIiwgInNjYWxlPTUxMjoyODgiLCAiT1VUIl0sCiAgICBjYXB0dXJlX291dHB1dD1UcnVlKQppbXBvcnQgc2h1dGlsCnNodXRpbC5ybXRyZWUoZmQsIGlnbm9yZV9lcnJvcnM9VHJ1ZSkKcHJpbnQoIlNBVkVEIiBpZiBvcy5wYXRoLmV4aXN0cygiT1VUIikgZWxzZSAiRkFJTEVEIikKIiIiLnJlcGxhY2UoIlBST01QVF9QTEFDRUhPTERFUiIsIHByb21wdCkucmVwbGFjZSgiU1RFUFMiLCBzdHIoc3RlcHMpKS5yZXBsYWNlKCJGUkFNRVMiLCBzdHIoZnJhbWVzKSkucmVwbGFjZSgiRlBTIiwgc3RyKGZwcykpLnJlcGxhY2UoIk9VVCIsIG91dCkKICAgICAgICAgICAgc3Rkb3V0LCBzdGRlcnIgPSBydW5fZ2VuKGNvZGUsIDYwMCkKICAgICAgICAgICAgbG9nKGYiVmlkZW86IHtzdGRvdXRbLTYwOl19IikKICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMob3V0KToKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsic3RhdHVzIjogIm9rIiwgInBhdGgiOiBvdXQsCiAgICAgICAgICAgICAgICAgICAgInVybCI6ICJodHRwOi8vMTkyLjE2OC4xMC45NDozMzMzL2ZpbGUvdmlkZW9fIiArIHRzICsgIi5tcDQifSkKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsic3RhdHVzIjogImVycm9yIiwgImVycm9yIjogc3RkZXJyWy0zMDA6XX0pCgogICAgICAgIGVsaWYgIi9nZW5lcmF0ZS0zZCIgaW4gcDoKICAgICAgICAgICAgcHJvbXB0ID0gc3RyKGJvZHkuZ2V0KCJwcm9tcHQiLCAiYSBkZXRhaWxlZCBiaXJkIikpLnJlcGxhY2UoJyInLCAiJyIpCiAgICAgICAgICAgIG9kID0gR0VOICsgIi8zZF8iICsgdHMKICAgICAgICAgICAgb3MubWFrZWRpcnMob2QsIGV4aXN0X29rPVRydWUpCiAgICAgICAgICAgIGNvZGUgPSAiIiIKaW1wb3J0IHN5cywgb3MKdHJ5OgogICAgZnJvbSBzaGFwX2UuZGlmZnVzaW9uLnNhbXBsZSBpbXBvcnQgc2FtcGxlX2xhdGVudHMKICAgIGZyb20gc2hhcF9lLmRpZmZ1c2lvbi5nYXVzc2lhbl9kaWZmdXNpb24gaW1wb3J0IGRpZmZ1c2lvbl9mcm9tX2NvbmZpZwogICAgZnJvbSBzaGFwX2UubW9kZWxzLmRvd25sb2FkIGltcG9ydCBsb2FkX21vZGVsLCBsb2FkX2NvbmZpZwogICAgZnJvbSBzaGFwX2UudXRpbC5ub3RlYm9va3MgaW1wb3J0IGNyZWF0ZV9wYW5fY2FtZXJhcywgZGVjb2RlX2xhdGVudF9pbWFnZXMsIGRlY29kZV9sYXRlbnRfbWVzaAogICAgZnJvbSBzaGFwX2UudXRpbC5pbWFnZV91dGlsIGltcG9ydCBsaW5lYXJfdG9fc3JnYgogICAgZnJvbSBQSUwgaW1wb3J0IEltYWdlCiAgICBpbXBvcnQgdG9yY2gsIG51bXB5IGFzIG5wCiAgICBkZXYgPSAiY3B1IgogICAgeG0gPSBsb2FkX21vZGVsKCJ0cmFuc21pdHRlciIsIGRldmljZT1kZXYpCiAgICBtb2RlbCA9IGxvYWRfbW9kZWwoInRleHQzMDBNIiwgZGV2aWNlPWRldikKICAgIGRpZmYgPSBkaWZmdXNpb25fZnJvbV9jb25maWcobG9hZF9jb25maWcoImRpZmZ1c2lvbiIpKQogICAgbGF0ZW50cyA9IHNhbXBsZV9sYXRlbnRzKGJhdGNoX3NpemU9MSwgbW9kZWw9bW9kZWwsIGRpZmZ1c2lvbj1kaWZmLAogICAgICAgIGd1aWRhbmNlX3NjYWxlPTE1LjAsCiAgICAgICAgbW9kZWxfa3dhcmdzPWRpY3QodGV4dHM9WyJQUk9NUFQsIGhpZ2hseSBkZXRhaWxlZCwgcmVhbGlzdGljIHByb3BvcnRpb25zIl0pLAogICAgICAgIHByb2dyZXNzPUZhbHNlLCBjbGlwX2Rlbm9pc2VkPVRydWUsIHVzZV9mcDE2PUZhbHNlLAogICAgICAgIHVzZV9rYXJyYXM9VHJ1ZSwga2FycmFzX3N0ZXBzPTMyLCBzaWdtYV9taW49MWUtMywgc2lnbWFfbWF4PTE2MCwgc19jaHVybj0wKQogICAgdCA9IGRlY29kZV9sYXRlbnRfbWVzaCh4bSwgbGF0ZW50c1swXSkudHJpX21lc2goKQogICAgd2l0aCBvcGVuKCJPVVRESVIvbW9kZWwub2JqIiwgInciKSBhcyBmOgogICAgICAgIHQud3JpdGVfb2JqKGYpCiAgICBjYW1zID0gY3JlYXRlX3Bhbl9jYW1lcmFzKDEyOCwgZGV2KQogICAgaW1ncyA9IGRlY29kZV9sYXRlbnRfaW1hZ2VzKHhtLCBsYXRlbnRzWzBdLCBjYW1zLCByZW5kZXJpbmdfbW9kZT0ibmVyZiIpCiAgICBmcmFtZXMgPSBbSW1hZ2UuZnJvbWFycmF5KChsaW5lYXJfdG9fc3JnYihpbWcuZGV0YWNoKCkuY3B1KCkubnVtcHkoKSkqMjU1KS5hc3R5cGUobnAudWludDgpKSBmb3IgaW1nIGluIGltZ3NdCiAgICBmcmFtZXNbMF0uc2F2ZSgiT1VURElSL3ByZXZpZXcucG5nIikKICAgIGZyYW1lc1swXS5zYXZlKCJPVVRESVIvcHJldmlldy5naWYiLCBzYXZlX2FsbD1UcnVlLCBhcHBlbmRfaW1hZ2VzPWZyYW1lc1sxOl0sIGxvb3A9MCwgZHVyYXRpb249ODApCiAgICBwcmludCgiT0siKQpleGNlcHQgSW1wb3J0RXJyb3I6CiAgICBpbXBvcnQgc3VicHJvY2VzcwogICAgc3VicHJvY2Vzcy5ydW4oW3N5cy5leGVjdXRhYmxlLCAiLW0iLCAicGlwIiwgImluc3RhbGwiLCAic2hhcC1lIiwgIi1xIl0sIGNhcHR1cmVfb3V0cHV0PVRydWUpCiAgICBwcmludCgiSU5TVEFMTElOR19TSEFQX0UiKQpleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICBwcmludCgiRVJSOiIgKyBzdHIoZSlbOjIwMF0pCiIiIi5yZXBsYWNlKCJQUk9NUFQiLCBwcm9tcHQpLnJlcGxhY2UoIk9VVERJUiIsIG9kKQogICAgICAgICAgICBzdGRvdXQsIHN0ZGVyciA9IHJ1bl9nZW4oY29kZSwgMzAwKQogICAgICAgICAgICBsb2coZiIzRDoge3N0ZG91dFstODA6XX0iKQogICAgICAgICAgICByZXMgPSB7InN0YXR1cyI6ICJvayIsICJpbmZvIjogc3Rkb3V0Wy0xMDA6XX0KICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMob2QgKyAiL21vZGVsLm9iaiIpOgogICAgICAgICAgICAgICAgcmVzWyJvYmpfdXJsIl0gPSAiaHR0cDovLzE5Mi4xNjguMTAuOTQ6MzMzMy9maWxlLzNkXyIgKyB0cyArICIvbW9kZWwub2JqIgogICAgICAgICAgICBpZiBvcy5wYXRoLmV4aXN0cyhvZCArICIvcHJldmlldy5wbmciKToKICAgICAgICAgICAgICAgIHJlc1sicHJldmlld191cmwiXSA9ICJodHRwOi8vMTkyLjE2OC4xMC45NDozMzMzL2ZpbGUvM2RfIiArIHRzICsgIi9wcmV2aWV3LnBuZyIKICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMob2QgKyAiL3ByZXZpZXcuZ2lmIik6CiAgICAgICAgICAgICAgICByZXNbImdpZl91cmwiXSA9ICJodHRwOi8vMTkyLjE2OC4xMC45NDozMzMzL2ZpbGUvM2RfIiArIHRzICsgIi9wcmV2aWV3LmdpZiIKICAgICAgICAgICAgaWYgbm90IHJlcy5nZXQoIm9ial91cmwiKToKICAgICAgICAgICAgICAgIHJlc1sic3RhdHVzIl0gPSAiZ2VuZXJhdGluZyIKICAgICAgICAgICAgc2VsZi5zZW5kX2pzb24ocmVzKQoKICAgICAgICBlbGlmICIvZ2VuZXJhdGUtYXVkaW8iIGluIHA6CiAgICAgICAgICAgIHRleHQgPSBzdHIoYm9keS5nZXQoInRleHQiLCBib2R5LmdldCgicHJvbXB0IiwgIkhlbGxvIGZyb20gVk5UIikpKQogICAgICAgICAgICBvdXQgPSBHRU4gKyAiL2F1ZGlvXyIgKyB0cyArICIud2F2IgogICAgICAgICAgICBhaWZmID0gb3V0LnJlcGxhY2UoIi53YXYiLCAiLmFpZmYiKQogICAgICAgICAgICBzdWJwcm9jZXNzLnJ1bihbInNheSIsICItbyIsIGFpZmYsICItLWRhdGEtZm9ybWF0PUxFRjMyQDIyMDUwIiwgdGV4dF0sIHRpbWVvdXQ9MzApCiAgICAgICAgICAgIHN1YnByb2Nlc3MucnVuKFsiZmZtcGVnIiwgIi15IiwgIi1pIiwgYWlmZiwgb3V0XSwgY2FwdHVyZV9vdXRwdXQ9VHJ1ZSwgdGltZW91dD0xNSkKICAgICAgICAgICAgaWYgbm90IG9zLnBhdGguZXhpc3RzKG91dCkgYW5kIG9zLnBhdGguZXhpc3RzKGFpZmYpOgogICAgICAgICAgICAgICAgb3MucmVuYW1lKGFpZmYsIG91dCkKICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMob3V0KSBhbmQgb3MucGF0aC5nZXRzaXplKG91dCkgPiAxMDA6CiAgICAgICAgICAgICAgICBzZWxmLnNlbmRfanNvbih7InN0YXR1cyI6ICJvayIsCiAgICAgICAgICAgICAgICAgICAgInVybCI6ICJodHRwOi8vMTkyLjE2OC4xMC45NDozMzMzL2ZpbGUvYXVkaW9fIiArIHRzICsgIi53YXYifSkKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsic3RhdHVzIjogImVycm9yIiwgImVycm9yIjogImF1ZGlvIGdlbmVyYXRpb24gZmFpbGVkIn0pCgogICAgICAgIGVsaWYgIi9nZW5lcmF0ZSIgaW4gcDoKICAgICAgICAgICAgcHJvbXB0ID0gc3RyKGJvZHkuZ2V0KCJwcm9tcHQiLCAicGhvdG9yZWFsaXN0aWMgYmlyZCIpKS5yZXBsYWNlKCciJywgIiciKQogICAgICAgICAgICB3ID0gbWluKGludChib2R5LmdldCgid2lkdGgiLCA1MTIpKSwgNzY4KQogICAgICAgICAgICBoID0gbWluKGludChib2R5LmdldCgiaGVpZ2h0IiwgNTEyKSksIDc2OCkKICAgICAgICAgICAgc3RlcHMgPSBpbnQoYm9keS5nZXQoInN0ZXBzIiwgMjApKQogICAgICAgICAgICBvdXQgPSBHRU4gKyAiL2ltZ18iICsgdHMgKyAiLnBuZyIKICAgICAgICAgICAgZW5oYW5jZWQgPSBwcm9tcHQgKyAiLCA4ayB1aGQsIHBob3RvcmVhbGlzdGljLCBtYXN0ZXJwaWVjZSwgc2hhcnAgZm9jdXMsIGJlc3QgcXVhbGl0eSIKICAgICAgICAgICAgbmVnID0gImJsdXJyeSwgbG93IHF1YWxpdHksIHVnbHksIGRpc3RvcnRlZCwgd2F0ZXJtYXJrLCB0ZXh0LCBiYWQgYW5hdG9teSIKICAgICAgICAgICAgY29kZSA9ICIiIgppbXBvcnQgdG9yY2gsIG9zCmZyb20gZGlmZnVzZXJzIGltcG9ydCBTdGFibGVEaWZmdXNpb25QaXBlbGluZQpkZXZpY2UgPSAibXBzIiBpZiB0b3JjaC5iYWNrZW5kcy5tcHMuaXNfYXZhaWxhYmxlKCkgZWxzZSAiY3B1IgpkdHlwZSA9IHRvcmNoLmZsb2F0MTYgaWYgZGV2aWNlID09ICJtcHMiIGVsc2UgdG9yY2guZmxvYXQzMgpwaXBlID0gU3RhYmxlRGlmZnVzaW9uUGlwZWxpbmUuZnJvbV9wcmV0cmFpbmVkKAogICAgInJ1bndheW1sL3N0YWJsZS1kaWZmdXNpb24tdjEtNSIsIHRvcmNoX2R0eXBlPWR0eXBlLCBzYWZldHlfY2hlY2tlcj1Ob25lKQpwaXBlID0gcGlwZS50byhkZXZpY2UpCnBpcGUuZW5hYmxlX2F0dGVudGlvbl9zbGljaW5nKCkKaW1nID0gcGlwZSgiUFJPTVBUIiwgbmVnYXRpdmVfcHJvbXB0PSJORUciLAogICAgbnVtX2luZmVyZW5jZV9zdGVwcz1TVEVQUywgd2lkdGg9V0lEVEgsIGhlaWdodD1IRUlHSFQsCiAgICBndWlkYW5jZV9zY2FsZT03LjUpLmltYWdlc1swXQppbWcuc2F2ZSgiT1VUIikKcHJpbnQoIlNBVkVEIikKIiIiLnJlcGxhY2UoIlBST01QVCIsIGVuaGFuY2VkKS5yZXBsYWNlKCJORUciLCBuZWcpLnJlcGxhY2UoIlNURVBTIiwgc3RyKHN0ZXBzKSkucmVwbGFjZSgiV0lEVEgiLCBzdHIodykpLnJlcGxhY2UoIkhFSUdIVCIsIHN0cihoKSkucmVwbGFjZSgiT1VUIiwgb3V0KQogICAgICAgICAgICBzdGRvdXQsIHN0ZGVyciA9IHJ1bl9nZW4oY29kZSwgMzAwKQogICAgICAgICAgICBsb2coZiJJbWFnZToge3N0ZG91dFstNDA6XX0ge3N0ZGVyclstNDA6XX0iKQogICAgICAgICAgICBpZiBvcy5wYXRoLmV4aXN0cyhvdXQpOgogICAgICAgICAgICAgICAgc2VsZi5zZW5kX2pzb24oeyJzdGF0dXMiOiAib2siLCAicGF0aCI6IG91dCwKICAgICAgICAgICAgICAgICAgICAidXJsIjogImh0dHA6Ly8xOTIuMTY4LjEwLjk0OjMzMzMvZmlsZS9pbWdfIiArIHRzICsgIi5wbmcifSkKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHNlbGYuc2VuZF9qc29uKHsic3RhdHVzIjogImVycm9yIiwgImVycm9yIjogc3RkZXJyWy00MDA6XX0pCiAgICAgICAgZWxzZToKICAgICAgICAgICAgc2VsZi5zZW5kX2pzb24oeyJlcnJvciI6ICJ1bmtub3duOiAiICsgcH0sIDQwNCkKCmxvZygiVk5UIFN0dWRpbyBBUEkgdjMuMiBzdGFydGluZyBvbiBwb3J0IDMzMzMiKQpsb2coZiJQeXRob246IHtQWX0iKQpsb2coZiJDb21meVVJOiB7J09OTElORScgaWYgY29tZnlfYWxpdmUoKSBlbHNlICdvZmZsaW5lJ30iKQpsb2coZiJHZW4gZGlyOiB7R0VOfSIpCnRyeToKICAgIHNlcnZlciA9IGh0dHAuc2VydmVyLkhUVFBTZXJ2ZXIoKCIwLjAuMC4wIiwgMzMzMyksIEgpCiAgICBsb2coIkFQSSBPTkxJTkUgLSByZWFkeSBmb3IgcmVxdWVzdHMiKQogICAgc2VydmVyLnNlcnZlX2ZvcmV2ZXIoKQpleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICBsb2coZiJGQVRBTDoge2V9IikKICAgIGltcG9ydCBzeXM7IHN5cy5leGl0KDEpCg=='))\" "
    o,e=ssh(write_cmd,30)
    lines,_=ssh("wc -l /Users/alias/vnt-studio/studio_api.py 2>/dev/null || echo MISSING")
    print(f"  File after write: {lines}")

# Step 3: Check Python path
print("[3] Verifying Python...")
py_check,e=ssh(PY+" --version 2>&1")
print(f"  Python: {py_check}")
if not py_check or "not found" in py_check.lower():
    # Find correct python
    py_find,_=ssh("which python3 2>/dev/null || ls /Users/alias/miniforge3/bin/python* 2>/dev/null | head -3")
    print(f"  Alt Python: {py_find}")
    PY=py_find.split("\n")[0].strip() if py_find else "/usr/bin/python3"
    print(f"  Using: {PY}")

# Step 4: Kill old, start fresh
print("[4] Starting API...")
ssh("lsof -ti:3333 | xargs kill -9 2>/dev/null; sleep 1")
ssh("pkill -f studio_api 2>/dev/null; sleep 1")
ssh(f"nohup {PY} /Users/alias/vnt-studio/studio_api.py > /tmp/studio.log 2>&1 &")
print("  Waiting 12s...")
time.sleep(12)

# Step 5: Verify
online,h=check_api(t=8)
print(f"  API: {'ONLINE' if online else 'OFFLINE'}")
if h: print(f"  Response: {str(h)[:120]}")

if not online:
    log_o,_=ssh("tail -25 /tmp/studio.log")
    print(f"  Log:\n{log_o[:500]}")
    
    # Check if it's a Python issue
    py_test,pe=ssh(f"{PY} -c \"print('python ok')\" 2>&1")
    print(f"  Python test: {py_test} {pe[:60]}")
    
    # Try starting with logging to check
    ssh("lsof -ti:3333 | xargs kill -9 2>/dev/null; sleep 1")
    ssh(f"{PY} /Users/alias/vnt-studio/studio_api.py >> /tmp/studio.log 2>&1 &")
    time.sleep(8)
    online,h=check_api(t=8)
    log2,_=ssh("tail -15 /tmp/studio.log")
    print(f"  Retry: {'ONLINE' if online else 'OFFLINE'} log={log2[:200]}")

# Step 6: Install launchd for auto-restart
if online:
    print("[5] Installing launchd auto-start...")
    plist=f"""<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\"><dict>
<key>Label</key><string>com.vnt.studio</string>
<key>ProgramArguments</key><array>
<string>{PY}</string>
<string>/Users/alias/vnt-studio/studio_api.py</string></array>
<key>RunAtLoad</key><true/>
<key>KeepAlive</key><true/>
<key>StandardOutPath</key><string>/tmp/studio.log</string>
<key>StandardErrorPath</key><string>/tmp/studio.log</string>
</dict></plist>"""
    open("/tmp/vnt.studio.plist","w").write(plist)
    scp("/tmp/vnt.studio.plist","/Users/alias/Library/LaunchAgents/com.vnt.studio.plist")
    ssh("launchctl unload /Users/alias/Library/LaunchAgents/com.vnt.studio.plist 2>/dev/null; launchctl load /Users/alias/Library/LaunchAgents/com.vnt.studio.plist 2>/dev/null")
    print("  Launchd: installed")

# Step 7: Run quick tests
print("\n[6] Running tests...")
RESULTS={}

def post(ep,data,t=300):
    try:
        body=json.dumps(data).encode()
        req=urllib.request.Request(f"http://{M4}:3333{ep}",data=body,
            headers={"Content-Type":"application/json"},method="POST")
        with urllib.request.urlopen(req,timeout=t) as r:
            return json.loads(r.read()),None
    except Exception as e:
        return None,str(e)

if online:
    # Test 1: Image bird
    print("  Test 1: Image (bird)...")
    r,e=post("/generate",{"prompt":"photorealistic eagle sharp 8k","width":512,"height":512,"steps":20},300)
    RESULTS["Image_Bird"]=("PASS",r.get("url","")) if r and r.get("status")=="ok" else ("FAIL",str(e or r)[:60])
    print(f"    {RESULTS['Image_Bird']}")
    time.sleep(1)

    # Test 2: Image car
    print("  Test 2: Image (car)...")
    r,e=post("/generate",{"prompt":"red ferrari sports car photorealistic 8k","width":512,"height":512,"steps":20},300)
    RESULTS["Image_Car"]=("PASS",r.get("url","")) if r and r.get("status")=="ok" else ("FAIL",str(e or r)[:60])
    print(f"    {RESULTS['Image_Car']}")
    time.sleep(1)

    # Test 3: Audio (fast test first)
    print("  Test 3: Audio (speech)...")
    r,e=post("/generate-audio",{"text":"VNT World AI Division. All systems operational."},60)
    RESULTS["Audio"]=("PASS",r.get("url","")) if r and r.get("status")=="ok" else ("FAIL",str(e or r)[:60])
    print(f"    {RESULTS['Audio']}")
    time.sleep(1)

    # Test 4: Video
    print("  Test 4: Video...")
    r,e=post("/generate-video",{"prompt":"birds flying over lake cinematic","frames":6,"fps":8,"steps":12},500)
    RESULTS["Video"]=("PASS",r.get("url","")) if r and r.get("status")=="ok" else ("FAIL",str(e or r)[:60])
    print(f"    {RESULTS['Video']}")
    time.sleep(1)

    # Test 5: 3D
    print("  Test 5: 3D model...")
    r,e=post("/generate-3d",{"prompt":"realistic bird dove with wings"},300)
    RESULTS["3D"]=("PASS",r.get("obj_url") or r.get("preview_url","generating")) if r and (r.get("obj_url") or r.get("preview_url") or r.get("status")=="generating") else ("FAIL",str(e or r)[:60])
    print(f"    {RESULTS['3D']}")

    # Test 6: File list
    try:
        with urllib.request.urlopen(f"http://{M4}:3333/list",timeout=8) as resp:
            fl=json.loads(resp.read())
            RESULTS["FileList"]=("PASS",f"{fl.get('count',0)} files")
    except Exception as ex:
        RESULTS["FileList"]=("FAIL",str(ex)[:60])
    print(f"    FileList: {RESULTS['FileList']}")

else:
    for n in ["Image_Bird","Image_Car","Audio","Video","3D","FileList"]:
        RESULTS[n]=("FAIL","API offline")

# Step 8: Update media.html status indicator
print("\n[7] Updating media dashboard...")
media_path=WEB+"/media.html"
if os.path.exists(media_path):
    media=open(media_path).read()
    # Fix API URL if wrong
    if "localhost:3333" in media:
        media=media.replace("localhost:3333","192.168.10.94:3333")
    if "127.0.0.1:3333" in media:
        media=media.replace("127.0.0.1:3333","192.168.10.94:3333")
    # Add auto-reconnect script if not present
    if "auto-reconnect" not in media and "</body>" in media:
        reconnect_js="""
<script>
// Auto-reconnect: retry API every 30s if offline
window._apiRetry = setInterval(async () => {
  try {
    const r = await fetch('http://192.168.10.94:3333/health', {signal: AbortSignal.timeout(5000)});
    if (r.ok) {
      const d = await r.json();
      if (d.status === 'online') {
        clearInterval(window._apiRetry);
        location.reload();
      }
    }
  } catch(e) {}
}, 30000);
// auto-reconnect
</script>"""
        media=media.replace("</body>",reconnect_js+"</body>")
    open(media_path,"w").write(media)
    print("  media.html: API URL fixed + auto-reconnect added")

# Step 9: Summary + email
passed=sum(1 for v in RESULTS.values() if v[0]=="PASS")
total=len(RESULTS)
api_txt="ONLINE" if online else "OFFLINE"

save("\n".join([
    f"M4 Studio Fix Complete {TS}",
    f"API: {api_txt}",
    f"Tests: {passed}/{total}",
]+[f"  {n}: {s} {d[:50]}" for n,(s,d) in RESULTS.items()]))

print(f"\n=======================================================")
print(f"API: {api_txt} | Tests: {passed}/{total}")
for n,(s,d) in RESULTS.items():
    print(f"  [{'PASS' if s=='PASS' else 'FAIL'}] {n}: {d[:60]}")

# Send email
try:
    msg=MIMEMultipart()
    msg["From"]=f"Alias CEO VNT <aliasvnt@gmail.com>"
    msg["To"]="kraheelw@yahoo.com"
    msg["Subject"]=f"M4 Studio {api_txt} | {passed}/{total} Tests | {TS}"
    lines=[f"M4 Studio Status: {api_txt}",f"Tests: {passed}/{total}",""]
    for n,(s,d) in RESULTS.items():
        lines.append(f"  [{'PASS' if s=='PASS' else 'FAIL'}] {n}: {d[:70]}")
    lines+=["","API: http://192.168.10.94:3333/health","ComfyUI: http://192.168.10.94:7861",
        "","Alias - CEO VNT"]
    msg.attach(MIMEText("\n".join(lines),"plain"))
    with smtplib.SMTP("smtp.gmail.com",587,timeout=20) as s:
        s.ehlo();s.starttls();s.login("aliasvnt@gmail.com","xkuzasikrrukorvg");s.send_message(msg)
    print("Email sent")
except Exception as e:
    print(f"Email: {str(e)[:60]}")
