
import subprocess,os,ast,time,datetime
MP="/mnt/vnt-data/FileServer/VNT_World_AI_Division/MemPalace.md"
SYSTEMD="/etc/systemd/system"
def run(c,shell=False,t=20):
    r=subprocess.run(c,shell=shell,capture_output=True,text=True,timeout=t)
    return r.stdout.strip()
def save(e):
    ts=datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    try:open(MP,"a").write("\n### ZeusInst ["+ts+"]\n"+str(e)+"\n")
    except:pass
print("STEP5: ZEUS MONITOR")
monitor=chr(10).join([
    "#!/usr/bin/env python3",
    "import subprocess,time,datetime,json,smtplib,os,urllib.request",
    "from email.mime.text import MIMEText",
    "from email.mime.multipart import MIMEMultipart",
    "MP='/mnt/vnt-data/FileServer/VNT_World_AI_Division/MemPalace.md'",
    "CFG='/mnt/vnt-data/FileServer/VNT_World_AI_Division/vnt_config.json'",
    "RCA='/mnt/vnt-data/FileServer/VNT_World_AI_Division/rca_log.json'",
    "WEB='/home/k/vnt-web'",
    "LAST=[0];DOWN={};UP={}",
    "AGENTS=[",
    "    ('alias-voice-agent','Alias','CEO',8443,'Ryan'),",
    "    ('zeus-agent','Zeus','IT Director',7777,'Alias'),",
    "    ('maya-agent','Maya','Finance',7778,'Alias'),",
    "    ('ava-agent','Ava','Files',7779,'Alias'),",
    "    ('julian-agent','Julian','PM',7780,'Alias'),",
    "    ('ethan-agent','Dr. Ethan','Medical',7781,'Alias'),",
    "    ('lee-agent','Lee','Marketing',7782,'Alias'),",
    "    ('amr-agent','Amr','Legal',7783,'Alias'),",
    "    ('nova-agent','Nova','Architect',7784,'Alias'),",
    "    ('vnt-webserver','Mia','Reception',9999,'Alias'),",
    "    ('specter-agent','Specter','CyberSec',7788,'Alias'),",
    "    ('dina-agent','Dina','Nurse',7786,'Ethan'),",
    "    ('luc-agent','Luc','Developer',7787,'Zeus'),",
    "    ('ben-agent','Ben','IT Ops',7789,'Zeus'),",
    "    ('jodi-agent','Jodi','Research',7790,'Alias'),",
    "    ('rick-agent','Rick','TechRes',7791,'Alias'),",
    "]",
    "EXTRA=['alias-email-reader','vnt-simulation','github-relay','smbd']",
    "def save(e):",
    "    ts=datetime.datetime.now().strftime('%Y-%m-%d %H:%M')",
    "    try:open(MP,'a').write('\\n### Zeus ['+ts+']\\n'+str(e)+'\\n')",
    "    except:pass",
    "def cfg():",
    "    try:return json.load(open(CFG))",
    "    except:return {}",
    "def cause(svc,logs):",
    "    if not os.path.exists('/etc/systemd/system/'+svc+'.service'):return 'No unit file','Create unit file','Create at deploy'",
    "    if 'No such file' in logs:return 'Script missing','Recreate script','Store paths in config'",
    "    if 'Errno 98' in logs:return 'Port conflict','fuser -k','SO_REUSEADDR'",
    "    if 'ModuleNotFoundError' in logs:return 'Missing module','pip install','Pre-install deps'",
    "    if 'SyntaxError' in logs:return 'Syntax error','Fix script','ast.parse before deploy'",
    "    return 'Runtime crash','Restart','try/except in main loop'",
    "def send_email(subj,body):",
    "    c=cfg()",
    "    try:",
    "        G=c['gmail_user'];P=c['gmail_app_password'];R=c['ryan_email']",
    "        msg=MIMEMultipart();msg['From']='Alias CEO VNT <'+G+'>';msg['To']=R;msg['Subject']=subj",
    "        msg.attach(MIMEText(body,'plain'))",
    "        with smtplib.SMTP('smtp.gmail.com',587,timeout=15) as s:",
    "            s.ehlo();s.starttls();s.login(G,P);s.send_message(msg)",
    "        save('Email: '+subj)",
    "    except Exception as e:save('Email fail: '+str(e))",
    "def wa(msg):",
    "    c=cfg()",
    "    try:",
    "        ph=c.get('ryan_phone','+966568116899')",
    "        body=json.dumps({'task':'Send WhatsApp to Ryan '+ph+': Alias: '+msg}).encode()",
    "        req=urllib.request.Request('http://127.0.0.1:7777/task',data=body,headers={'Content-Type':'application/json'},method='POST')",
    "        urllib.request.urlopen(req,timeout=8)",
    "    except:pass",
    "def update_page(st,wa_ok):",
    "    try:",
    "        rows='';ac=0",
    "        for svc,name,role,port,rt in AGENTS:",
    "            active=st.get(svc,False)",
    "            if active:ac+=1",
    "            dot='#00cc55' if active else '#cc2222'",
    "            s=('<span style=\"color:#00cc55;font-weight:600\">Active</span>' if active else '<span style=\"color:#cc4444;font-weight:600\">Offline</span>')",
    "            wt='' ",
    "            if name=='Alias':wt=' <small style=\"background:#075e54;color:#dcf8c6;border-radius:3px;padding:1px 5px;font-size:9px\">WA</small>'",
    "            rows+=('<tr><td style=\"padding:8px 4px 8px 14px\"><span style=\"display:inline-block;width:8px;height:8px;border-radius:50%;background:'+dot+'\"></span></td>'",
    "                +'<td style=\"padding:8px 12px;font-weight:600;color:#e0ffe0\">'+name+wt+'</td>'",
    "                +'<td style=\"padding:8px 12px;color:#7ab87a;font-size:12px\">'+role+'</td>'",
    "                +'<td style=\"padding:8px 12px;color:#556655;font-size:12px\">'+rt+'</td>'",
    "                +'<td style=\"padding:8px 12px;color:#334433;font-size:11px;font-family:monospace\">:'+str(port)+'</td>'",
    "                +'<td style=\"padding:8px 14px\">'+s+'</td></tr>')",
    "        ts=datetime.datetime.now().strftime('%Y-%m-%d %H:%M')",
    "        wc='#25d366' if wa_ok else '#f85149'",
    "        css=('*{margin:0;padding:0;box-sizing:border-box}body{background:#0d1117;color:#c9d1d9;font-family:Segoe UI,Arial,sans-serif}.h{background:#161b22;border-bottom:1px solid #21262d;padding:14px 24px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px}.lo{font-size:17px;font-weight:700;color:#58a6ff}.su{font-size:11px;color:#484f58;margin-top:2px}.st{display:flex;gap:20px}.sn{font-size:18px;font-weight:700;text-align:center}.sl{font-size:9px;color:#484f58;text-transform:uppercase;letter-spacing:1px;text-align:center}.sc{padding:14px 24px}.se{font-size:10px;color:#484f58;text-transform:uppercase;letter-spacing:2px;margin-bottom:10px}.lk{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.bt{padding:6px 13px;border-radius:6px;font-size:12px;font-weight:500;text-decoration:none;border:1px solid;display:inline-block}.bg{background:rgba(35,134,54,.12);border-color:#238636;color:#3fb950}.bb{background:rgba(31,111,235,.12);border-color:#1f6feb;color:#58a6ff}.bo{background:rgba(158,106,3,.12);border-color:#9e6a03;color:#d29922}table{width:100%;border-collapse:collapse;background:#161b22;border:1px solid #21262d;border-radius:6px;overflow:hidden;margin-bottom:16px}thead th{background:#0d1117;color:#484f58;font-size:10px;text-transform:uppercase;letter-spacing:1px;padding:8px 12px;text-align:left;border-bottom:1px solid #21262d;font-weight:500}tbody tr{border-bottom:1px solid #1a2030}tbody tr:last-child{border-bottom:none}tbody tr:hover{background:#1c2128}.ft{padding:10px 24px;border-top:1px solid #21262d;font-size:10px;color:#30363d;text-align:center}')",
    "        off=len(AGENTS)-ac",
    "        html=('<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>VNT World AI Division</title><style>'+css+'</style></head><body>'",
    "            '<div class=\"h\"><div><div class=\"lo\">VNT World AI Division</div><div class=\"su\">Command Center | '+ts+' | Auto-refresh 60s</div></div>'",
    "            '<div class=\"st\"><div><div class=\"sn\" style=\"color:#3fb950\">'+str(ac)+'</div><div class=\"sl\">Active</div></div>'",
    "            '<div><div class=\"sn\" style=\"color:#f85149\">'+str(off)+'</div><div class=\"sl\">Offline</div></div>'",
    "            '<div><div class=\"sn\" style=\"color:'+wc+'\">'+('ON' if wa_ok else 'OFF')+'</div><div class=\"sl\">WA</div></div>'",
    "            '<div><div class=\"sn\">16</div><div class=\"sl\">Agents</div></div></div></div>'",
    "            '<div class=\"sc\"><div class=\"se\">Quick Access</div><div class=\"lk\">'",
    "            '<a href=\"https://192.168.10.96:8443\" class=\"bt bg\">Voice - Alias</a>'",
    "            '<a href=\"http://192.168.10.10\" class=\"bt bb\">Nextcloud</a>'",
    "            '<a href=\"http://192.168.10.96:8888/media.html\" class=\"bt bo\">Media Studio</a>'",
    "            '<a href=\"http://192.168.10.96:8888/generated/bird_house_proposal.html\" class=\"bt bg\">BirdHouse</a>'",
    "            '</div><div class=\"se\">Hierarchy - '+str(ac)+'/16</div>'",
    "            '<table><thead><tr><th></th><th>Agent</th><th>Role</th><th>Reports To</th><th>Port</th><th>Status</th></tr></thead><tbody>'+rows+'</tbody></table>'",
    "            '<div class=\"se\">Infrastructure</div>'",
    "            '<table><thead><tr><th>System</th><th>Address</th><th>Notes</th></tr></thead><tbody>'",
    "            '<tr><td style=\"padding:8px 14px;color:#e0ffe0\">MSI AI Server</td><td style=\"padding:8px 14px;font-family:monospace;color:#58a6ff;font-size:12px\">192.168.10.96</td><td style=\"padding:8px 14px;color:#484f58;font-size:12px\">Main AI brain</td></tr>'",
    "            '<tr><td style=\"padding:8px 14px;color:#e0ffe0\">M4 MacBook (ACTIVE)</td><td style=\"padding:8px 14px;font-family:monospace;color:#58a6ff;font-size:12px\">192.168.10.94:3333</td><td style=\"padding:8px 14px;color:#484f58;font-size:12px\">Media generation</td></tr>'",
    "            '<tr><td style=\"padding:8px 14px;color:#556655\">M2 (RETIRED)</td><td style=\"padding:8px 14px;font-family:monospace;color:#556655;font-size:12px\">not in use</td><td style=\"padding:8px 14px;color:#484f58;font-size:12px\">Retired</td></tr>'",
    "            '<tr><td style=\"padding:8px 14px;color:#e0ffe0\">Nextcloud CT104</td><td style=\"padding:8px 14px;font-family:monospace;color:#58a6ff;font-size:12px\">192.168.10.10</td><td style=\"padding:8px 14px;color:#484f58;font-size:12px\">File server</td></tr>'",
    "            '<tr><td style=\"padding:8px 14px;color:#e0ffe0\">Asusi7</td><td style=\"padding:8px 14px;font-family:monospace;color:#58a6ff;font-size:12px\">192.168.10.114</td><td style=\"padding:8px 14px;color:#484f58;font-size:12px\">SSH:Alias/116899</td></tr>'",
    "            '</tbody></table></div>'",
    "            '<div class=\"ft\">VNT World AI Division - Zeus Monitor - '+ts+'</div>'",
    "            '<script>setTimeout(()=>location.reload(),60000)</script></body></html>')",
    "        open(WEB+'/vnt_hierarchy.html','w').write(html)",
    "    except Exception as e:save('Hierarchy err: '+str(e))",
    "def cycle():",
    "    now=time.time();ts=datetime.datetime.now().strftime('%Y-%m-%d %H:%M')",
    "    statuses={};rca_ev=[];fixed=[];lines=[]",
    "    for svc,name,role,port,rt in AGENTS:",
    "        r=subprocess.run(['systemctl','is-active',svc],capture_output=True,text=True)",
    "        active=r.stdout.strip()=='active'",
    "        if not active:",
    "            if svc not in DOWN:DOWN[svc]=now",
    "            ds=int(now-DOWN[svc]);d_s=str(ds//60)+'m'+str(ds%60)+'s'",
    "            logs=subprocess.run(['journalctl','-u',svc,'-n','10','--no-pager','--quiet'],capture_output=True,text=True).stdout",
    "            ca,sol,prev=cause(svc,logs)",
    "            subprocess.run(['sudo','systemctl','restart',svc],capture_output=True,timeout=15)",
    "            time.sleep(2)",
    "            r2=subprocess.run(['systemctl','is-active',svc],capture_output=True,text=True)",
    "            rec=r2.stdout.strip()=='active'",
    "            if rec:UP[svc]=now;DOWN.pop(svc,None);fixed.append(name);active=True",
    "            ev={'ts':ts,'agent':name,'down':d_s,'cause':ca,'sol':sol,'prev':prev,'rec':rec}",
    "            rca_ev.append(ev)",
    "            try:",
    "                log=json.load(open(RCA)) if os.path.exists(RCA) else []",
    "                log.append(ev)",
    "                if len(log)>1000:log=log[-1000:]",
    "                json.dump(log,open(RCA,'w'),indent=2)",
    "            except:pass",
    "            save('RCA '+name+': '+ca+' down:'+d_s+' fixed:'+str(rec))",
    "        else:UP.setdefault(svc,now);DOWN.pop(svc,None)",
    "        statuses[svc]=active",
    "        us=int(now-UP.get(svc,now));u_s=str(us//3600)+'h'+str((us%3600)//60)+'m up'",
    "        lines.append(('OK' if active else 'DOWN')+' '+name+' - '+u_s)",
    "    for svc in EXTRA:",
    "        r=subprocess.run(['systemctl','is-active',svc],capture_output=True,text=True)",
    "        if r.stdout.strip()!='active':",
    "            subprocess.run(['sudo','systemctl','restart',svc],capture_output=True,timeout=15)",
    "            fixed.append(svc)",
    "    wa_r=subprocess.run(['systemctl','--user','is-active','alias-whatsapp'],capture_output=True,text=True)",
    "    wa_ok=wa_r.stdout.strip()=='active'",
    "    if not wa_ok:",
    "        subprocess.run(['systemctl','--user','restart','alias-whatsapp'],capture_output=True)",
    "        time.sleep(2)",
    "        wa_ok=subprocess.run(['systemctl','--user','is-active','alias-whatsapp'],capture_output=True,text=True).stdout.strip()=='active'",
    "        if wa_ok:fixed.append('WA')",
    "    update_page(statuses,wa_ok)",
    "    if now-LAST[0]>=3600:",
    "        LAST[0]=now;ac=sum(1 for x in statuses.values() if x)",
    "        bl=['VNT Hourly Report - '+ts,'','=== AGENTS ===']+lines",
    "        if rca_ev:",
    "            bl+=['','=== RCA ===']",
    "            for ev in rca_ev:",
    "                bl+=['Agent:'+ev['agent'],' Down:'+ev['down'],' Cause:'+ev['cause'],' Fix:'+ev['sol'],' Prevention:'+ev['prev'],'---']",
    "        if fixed:bl+=['','Fixed: '+', '.join(fixed)]",
    "        bl+=['','Hierarchy: http://192.168.10.96:8888/vnt_hierarchy.html','','- Alias CEO']",
    "        send_email('VNT Report '+ts+' | '+str(ac)+'/'+str(len(AGENTS))+(' | '+str(len(rca_ev))+' RCA' if rca_ev else ''),'\n'.join(bl))",
    "        wa('Report: '+str(ac)+'/'+str(len(AGENTS))+' active'+('. Fixed: '+','.join(fixed) if fixed else ''))",
    "save('Zeus monitor started')",
    "print('Zeus monitor active')",
    "LAST[0]=time.time()-3500",
    "while True:",
    "    try:cycle()",
    "    except Exception as e:save('Zeus err: '+str(e));print('Zeus err:',str(e))",
    "    time.sleep(300)",
])
try:
    ast.parse(monitor)
    open("/home/k/zeus-monitor.py","w").write(monitor)
    save("Zeus monitor written OK")
    print("  Zeus monitor: written+validated")
except SyntaxError as e:
    print("  Zeus monitor syntax error: "+str(e))
    import sys;sys.exit(1)
svc_path=SYSTEMD+"/zeus-monitor.service"
if not os.path.exists(svc_path):
    sf=chr(10).join(["[Unit]","Description=Zeus Self-Healing Monitor","After=network.target","",
        "[Service]","User=k","ExecStart=/usr/bin/python3 /home/k/zeus-monitor.py",
        "Restart=always","RestartSec=10","Environment=PYTHONUNBUFFERED=1","",
        "[Install]","WantedBy=multi-user.target"])
    open("/tmp/zm.s","w").write(sf)
    subprocess.run(["sudo","cp","/tmp/zm.s",svc_path],capture_output=True)
run(["sudo","systemctl","daemon-reload"])
run(["sudo","systemctl","enable","zeus-monitor"])
run(["sudo","systemctl","restart","zeus-monitor"],t=15)
time.sleep(3)
print("  Zeus monitor: "+run(["systemctl","is-active","zeus-monitor"]))
save("Zeus monitor installed")
print("STEP5 DONE")
